/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'teest' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* Keil::CMSIS Driver:GPIO@1.2.0 */
#define RTE_Drivers_GPIO0               /* Driver GPIO0 */
/* Keil::CMSIS Driver:USART@3.0.0 */
#define RTE_CMSIS_Driver_USART1         /* Driver USART1  */
#define RTE_CMSIS_Driver_USART2         /* Driver USART2  */
#define RTE_CMSIS_Driver_USART3         /* Driver USART3  */
#define RTE_CMSIS_Driver_USART4         /* Driver USART4  */
#define RTE_CMSIS_Driver_USART5         /* Driver USART5  */
#define RTE_CMSIS_Driver_USART6         /* Driver USART6  */
#define RTE_CMSIS_Driver_USART7         /* Driver USART7  */
#define RTE_CMSIS_Driver_USART8         /* Driver USART8  */
#define RTE_CMSIS_Driver_USART9         /* Driver USART9  */
#define RTE_CMSIS_Driver_USART9         /* Driver USART9  */
#define RTE_CMSIS_Driver_USART10        /* Driver USART10 */
#define RTE_CMSIS_Driver_USART11        /* Driver USART11 */
#define RTE_CMSIS_Driver_USART12        /* Driver USART12 */
#define RTE_CMSIS_Driver_USART13        /* Driver USART13 */
#define RTE_CMSIS_Driver_USART14        /* Driver USART14 */
#define RTE_CMSIS_Driver_USART15        /* Driver USART15 */
#define RTE_CMSIS_Driver_USART21        /* Driver USART21 (LPUART1) */
#define RTE_CMSIS_Driver_USART22        /* Driver USART22 (LPUART2) */
#define RTE_CMSIS_Driver_USART23        /* Driver USART23 (LPUART3) */
/* Keil::Compiler&ARM Compiler:Event Recorder&DAP@1.4.0 */
#define RTE_Compiler_EventRecorder
#define RTE_Compiler_EventRecorder_DAP


#endif /* RTE_COMPONENTS_H */
